Update armbian-build

diff --git a/armbian-build b/armbian-build
--- a/armbian-build
+++ b/armbian-build
@@ -112,7 +112,36 @@ generate_json() {
     echo "$json_output" | jq
 }
 
-generate_dialog() {
+# html output
+generate_html() {
+    local i=1
+    local command
+    local description
+    mapfile -t commands < <(printf '%s\n' "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}")
+
+    # Start HTML content
+    html_output="<html><body><h1>Armbian Build Framework Commands</h1><ul>"
+
+    for command in "${commands[@]}"; do
+        description="${COMMAND_DESCRIPTIONS_EN[${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}]}"
+        handler="${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}"
+
+        # Append HTML list item to the content
+        html_output+="<li><strong>$command</strong>: $description (Handler: $handler)</li>"
+
+        ((i++))
+    done
+
+    # End HTML content
+    html_output+="</ul></body></html>"
+
+    # Print the formatted HTML
+    echo "$html_output"
+}
+
+
+# TUI Menu
+generate_tui() {
 
     local i=0
     local command
@@ -138,8 +167,9 @@ generate_dialog() {
 
 	choice=$($DIALOG --title "Config Options" --menu "Choose an option:" 0 0 9 "${options[@]}" 3>&1 1>&2 2>&3)
 	echo -e "Choice $choice Result:\n\t ${results[$choice]}" | show_message
-}
+	}
 
+# TUI OK message
 show_message(){
 
     # Read the input from the pipe continuously until there is no more input
@@ -153,23 +183,77 @@ show_message(){
     clear
     }
 
+# Bash menu
+generate_menu() {
+    local i=1
+    local command
+    local description
+
+    echo "Config Options:"
+    for command in "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}"; do
+        description="${COMMAND_DESCRIPTIONS_EN[${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}]}"
+        handler="${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}"
+        echo "$i. $command - $description"
+        ((i++))
+    done
+
+    read -p "Choose an option (enter the number): " choice
+
+    if [[ $choice -ge 1 && $choice -le ${#ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]} ]]; then
+        echo -e "Choice $choice Result:\n\t []=\${[]}"
+    else
+        echo "Invalid choice. Please enter a valid number."
+    fi
+}
+
+generate_markdown() {
+    local i=1
+    local command
+    local description
+    mapfile -t commands < <(printf '%s\n' "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}")
+
+    # Start Markdown content
+    markdown_output="# Armbian Build Framework Commands\n"
+
+    for command in "${commands[@]}"; do
+        description="${COMMAND_DESCRIPTIONS_EN[${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}]}"
+        handler="${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}"
+
+        # Append Markdown list item to the content
+        markdown_output+="\n## $command\n- **Description:** $description\n- **Handler:** $handler\n"
+
+        ((i++))
+    done
+
+    # Print the formatted Markdown
+    echo -e "$markdown_output"
+}
+
 generate_help_message() {
     echo "Usage: $0 [options]"
     echo "Options:"
-    echo "  -h  Display this help message"
+    echo "  -h  Display this help message "
     echo "  -n  Generate Numbered output "
 	echo "  -j  Generate json output "
 	echo "  -t  Generate TUI output "
+    echo "  -b  Generate Bash menu output "
+    echo "  -m  Generate Markdown output "
+    echo "  -H  Generate HTML output "
 }
 
 # Call the function
-while getopts "hnjt" opt; do
+
+while getopts "bhHjmnt" opt; do
     case "$opt" in
-	h)  generate_help_message ; exit 1 ;;
-	n)  generate_descriptions ; exit 0 ;;
+
+	b)  generate_menu ; exit 0 ;;
+	h)  generate_help_message ; exit 0 ;;
+	H)  generate_html ; exit 0 ;;
 	j)  generate_json ; exit 0 ;;
-	t)  generate_dialog ; exit 0 ;;
-    *) echo "Invalid option"; generate_help_message; exit 1 ;;
+	m)  generate_markdown ; exit 0 ;;
+	n)  generate_descriptions ; exit 0 ;;
+	t)  generate_tui ; exit 0 ;;
+	*) echo "Invalid option"; generate_help_message; exit 1 ;;
     esac
 done
 
@@ -179,5 +263,5 @@ if [[ $1 == *"--"* ]]; then
 elif [[ -n $1 ]] && ! [[ $1 == --* || $1 == -* ]]; then
     bash ./compile.sh "$@"
 elif [[ -z $1 ]]; then
-     generate_help_message
+     generate_menu
 fi
