Update armbian-build
added tui output

diff --git a/armbian-build b/armbian-build
--- a/armbian-build
+++ b/armbian-build
@@ -8,6 +8,16 @@
 
 clear
 
+# Set the tui
+if command -v whiptail > /dev/null; then
+   DIALOG=whiptail
+elif command -v dialog > /dev/null; then
+   DIALOG=dialog
+else
+    echo "Error: Neither whiptail nor dialog is installed."
+    exit 1
+fi
+
 # More than one command can map to the same handler. In that case, use ARMBIAN_COMMANDS_TO_VARS_DICT for specific vars.
 declare -g -A ARMBIAN_COMMANDS_TO_HANDLERS_DICT=(
         ["docker"]="docker" # thus requires cli_docker_pre_run and cli_docker_run
@@ -102,6 +112,46 @@ generate_json() {
     echo "$json_output" | jq
 }
 
+generate_dialog() {
+
+    local i=0
+    local command
+    local description
+
+	if command -v whiptail > /dev/null; then
+	   local DIALOG=whiptail
+	elif command -v dialog > /dev/null; then
+	   local DIALOG=dialog
+	else
+	    echo "Error: Neither whiptail nor dialog is installed."
+	    exit 1
+	fi
+
+	for command in "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}"; do
+        description="${COMMAND_DESCRIPTIONS_EN[${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}]}"
+        handler="${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$command]}"
+        options+=("$i" "$command - $description")
+		results+=("[$command]=\"$handler\"")
+        ((i++))
+    done 
+
+
+	choice=$($DIALOG --title "Config Options" --menu "Choose an option:" 0 0 9 "${options[@]}" 3>&1 1>&2 2>&3)
+	echo -e "Choice $choice Result:\n\t ${results[$choice]}" | show_message
+}
+
+show_message(){
+
+    # Read the input from the pipe continuously until there is no more input
+    input=""
+    while read -r line; do
+        input+="$line\n"
+    done
+
+    # Display the "OK" message box with the input data
+    $DIALOG --title "Message Box" --msgbox "$input" 0 0
+    clear
+    }
 
 generate_help_message() {
     echo "Usage: $0 [options]"
@@ -109,14 +159,16 @@ generate_help_message() {
     echo "  -h  Display this help message"
     echo "  -n  Generate Numbered output "
 	echo "  -j  Generate json output "
+	echo "  -t  Generate TUI output "
 }
 
 # Call the function
-while getopts "hbjn" opt; do
+while getopts "hnjt" opt; do
     case "$opt" in
 	h)  generate_help_message ; exit 1 ;;
-	n)  generate_descriptions; exit 0 ;;
-	j)  generate_json; exit 0 ;;
+	n)  generate_descriptions ; exit 0 ;;
+	j)  generate_json ; exit 0 ;;
+	t)  generate_dialog ; exit 0 ;;
     *) echo "Invalid option"; generate_help_message; exit 1 ;;
     esac
 done
@@ -127,5 +179,5 @@ if [[ $1 == *"--"* ]]; then
 elif [[ -n $1 ]] && ! [[ $1 == --* || $1 == -* ]]; then
     bash ./compile.sh "$@"
 elif [[ -z $1 ]]; then
-    generate_help_message
+     generate_help_message
 fi
