Update armbian-build

diff --git a/armbian-build b/armbian-build
--- a/armbian-build
+++ b/armbian-build
@@ -1,219 +1,151 @@
 #!/usr/bin/env bash
 #
-# SPDX-License-Identifier: GPL-2.0
-# Copyright (c) 2013-2023 Tearran tearran@g...l.c.m
 
+#set -x
 
 # Initialise script
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 filename="$(basename "${BASH_SOURCE[0]}")"
 
-# Check if user is already in the working directory
-# load the source the data file
-if [ "$script_dir" != "$current_dir" ]; then
-    echo "Changing to working directory: $script_dir"
-    cd "$script_dir" || exit 1
-    # shellcheck source=/dev/null
-    source ./lib/functions/cli/commands.sh
-elif [ "$script_dir" == "$current_dir" ]; then
-    # shellcheck source=/dev/null
-    source ./lib/functions/cli/commands.sh
-else
-	echo "Error: Uknown "
-fi
-
-# Call the array from lib
-armbian_register_commands
-
-
-# Placeholder filler for tests
-filler_doc() {
-
-    # Set Foreground RED
-    clear && echo -e "\e[31m"
-
-	# HERE DOC
-    cat << EOF
-          █ █ █ █ █ █ █ █ █ █ █
-         ███████████████████████
-       ▄▄██                   ██▄▄
-       ▄▄██    ███████████    ██▄▄
-       ▄▄██   ██         ██   ██▄▄
-       ▄▄██   ██         ██   ██▄▄
-       ▄▄██   ██         ██   ██▄▄
-       ▄▄██   █████████████   ██▄▄
-       ▄▄██   ██         ██   ██▄▄
-       ▄▄██   ██         ██   ██▄▄
-       ▄▄██   ██         ██   ██▄▄
-       ▄▄██                   ██▄▄
-         ███████████████████████
-          █ █ █ █ █ █ █ █ █ █ █
-     Welcome to armbian-build system
-EOF
-
-    # Set Foreground Default
-    echo -e "\e[0m"
+source_data() {
+	# Check if user is already in the working directory
+	# load the source the data file
+	if [ "$script_dir" != "$current_dir" ]; then
+	    #echo -e "\nWarning: Not in working directory:\ncd $script_dir\nOK: Continuing\n\n"
+	    cd "$script_dir" || exit 1
+	    # shellcheck source=/dev/null
+	    source ./lib/functions/cli/commands.sh
+	    # Call the array from lib
+	    armbian_register_commands
+	elif [ "$script_dir" == "$current_dir" ]; then
+	    # shellcheck source=/dev/null
+	    source ./lib/functions/cli/commands.sh
+	    # Call the array from lib
+	    armbian_register_commands
+	else
+		echo "Error: Uknown "
+	fi
 }
 
-# Initialize variables to store metadata and options
-#title="configng"
-#title="armbian-config"
-#title="./compile.sh"
-title="armbian-build"
-uptitle=$(echo "$title" | tr '[:lower:]' '[:upper:]')
-section="1" # 1 for user doc
-version="0.0.0" # Comform to your format
-description="A command-line tool" # Short description
-options_list=("-h" "-l" "-r") # Short options/flags
+# This scripts help mesage
 
-# Descriptions for Short options/flags
-options_desc=("Display a help message and exit" "Expose all groups and functions" "Run the specified function within the specified group")
-author_list=("Tearran tearran@*hidden*" "Someone noreply@*hidden*") # Authors
-bug_report="https://github.com/Tearran/configng/issues" # Issues address
-date=$(date +"%B %d, %Y") # current date
-man_page="$title.$section" # file naming
-
-doc_build_system() {
-
-
-	# Function to generate documentation uses:
-	# YAML-like metadata header, Man page-like layout in Markdown format
-
-	# Markdown file name $title.1.md
-	cat << EOF   #> "$man_page.md"
----
-title: $uptitle
-section: $section
-header: User Manual
-footer: $title $version
-date: $date
-version: $version
----
-
-# NAME
-
-$uptitle - $description
-
-# DESCRIPTION
-
-The \`$title\` command is a command-line tool for $description. It provides a range of options for configuring various aspects of the system.
-
-# SYNOPSIS
-
-\`$title [OPTIONS] [CATEGORY] [FUNCTION]\`
-
-\`$title\` is the script name.
-
-[OPTIONS] are the available options.
-
-[CATEGORY] is the group/category.
-
-[FUNCTION] is the function within the specified group.
-
-# OPTIONS
-  -h, --help
-    Display a help message and exit.
-
-# EXAMPLES
-1. Display the help message:
-   \`$title -h\`
-
-
-# ENVIRONMENT
-
-Lists any environment variables that affect the behavior of the command.
-
-EOF
-    echo -e "\nARMBIAN_COMMANDS_TO_VARS_DICT:\n"
-    for key in "${!ARMBIAN_COMMANDS_TO_VARS_DICT[@]}"; do
-        echo "    $key -> ${ARMBIAN_COMMANDS_TO_VARS_DICT[$key]}"
-    done
-
-	echo -e "\n---\n"
-
-    echo -e "ARMBIAN_COMMANDS_TO_HANDLERS_DICT:\n"
-    for key in "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}"; do
-        echo -e "    $key -> ${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$key]}"
-    done
+help_message(){
 
 cat << EOF
+Help Usage: ./${filename} [ flag ] | [ OPTION=[var,var] .. ]
 
+  -h, --help       This help message and list of Build options.
 
-# SEE ALSO
+  -e, --examples   Place holder list of simple/basic Build[OPTIONS] and examples.
 
-Other relevant commands and resources.
+  -a, --advanced   Possible --flag option to list advanced Build[OPTIONS]
 
-# BUGS
+    , --handlers   Temp --flag to List Command Handlers Dictionary.
 
-Report bugs to <$bug_report>.
+    , --variable   Temp --flag to List Variables Dictionary.
 
-# AUTHORS
+For more detailed options, consult the examples help message.
 
-$(for author in "${author_list[@]}"; do echo "  $author"; done)
+EOF
+exit 0 ;
+
+}
+
+basic_message(){
+
+    echo -e "Usage: ./${filename} [OPTIONS=[VAR,VAR] [...]]"
+# TODO arrays and examples
+cat << EOF
+
+  BUILD_ONLY=["CSV"]           (u-boot, kernel, etc.).default NULL.
+
+  CLEAN_LEVEL=["CSV"]          Specify cleaning level (make, debs, etc.).
+
+  REPOSITORY_INSTALL=[unknown] Needed example.
+
+  BUILD_MINIMAL=["yes"]        Build a minimal CLI image default no/NULL.
+
+  BUILD_DESKTOP=["yes"]        Build an image with a minimal desktop, default no/NULL?.
+
+  EXTERNAL=[unknown]           Needed example.
+
+  BOARD=[unknown]              Needed example.
+
+  BRANCH=[unknown]             Needed example.
+
+  RELEASE=["CSV"]              Needed example.
+
+For more detailed options, consult the TODO: Advanced help message.
 
 EOF
 
-  echo "Documentation created: $man_page.md"
+exit 0 ;
+
 }
 
-generate_examples() {
+# Funtion to display advance and detaile options
+advanced_message(){
 
-	if command -v pandoc &> /dev/null
-	then
-	    echo "pandoc is installed at: $(which pandoc)"
-	    # Convert the Markdown documentation to a man page
+    echo -e "Usage: ./${filename} [OPTIONS]"
+    source_data
+    echo -e "\nARMBIAN_COMMANDS_TO_HANDLERS_DICT:\n"
+    for key in "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}"; do
+        echo -e "  $key -  ${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$key]}\n"
+    done
 
-		pandoc -s -f gfm -t man ./"$man_page.md" -o ./"$man_page"
+    echo -e "\nARMBIAN_COMMANDS_TO_VARS_DICT:"
+    for key in "${!ARMBIAN_COMMANDS_TO_VARS_DICT[@]}"; do
+        echo -e "  $key  -  ${ARMBIAN_COMMANDS_TO_VARS_DICT[$key]}\n"
+    done
 
-		# Display the man page
-		man ./"$man_page"
+	echo "For more detailed options, consult the full help message."
 
-		# Generate the HTML file using Pandoc
-		pandoc -s -f gfm -t html ./"$man_page.md" -o ./"$man_page.html"
+	exit 0 ;
 
-		# Modify the CSS styles in the HTML file to achieve a dark mode appearance
-		sed -i 's/color: #1a1a1a;/color: #eee;/; s/background-color: #fdfdfd;/background-color: #333;/' "$man_page.html"
-	else
-		echo
-	    echo "pandoc is not installed"
-		echo  "try:"
-		echo "sudo apt install pandoc"
-		echo ""
+}
 
-	fi
-
-	}
-
-# Display HANDLERS message
-if [ "$1" == "-H" ]; then
+# Display HANDLERS Dictionary
+if [[ "$1" == "--handlers" ]]; then
+    source_data
     echo "ARMBIAN_COMMANDS_TO_HANDLERS_DICT:"
     for key in "${!ARMBIAN_COMMANDS_TO_HANDLERS_DICT[@]}"; do
         echo "$key -> ${ARMBIAN_COMMANDS_TO_HANDLERS_DICT[$key]}"
     done
     exit 0 ;
 
-elif [[ "$1" == "--hidden" ]]; then
-
-    doc_build_system > "$man_page.md"
-	generate_examples
-	exit 0 ; 
-
-# Display VAR
-elif [ "$1" == "-V" ]; then
+# Display VAR Dictionary
+elif [[ "$1" == "--variable" ]]; then
+    source_data
     echo -e "\nARMBIAN_COMMANDS_TO_VARS_DICT:"
     for key in "${!ARMBIAN_COMMANDS_TO_VARS_DICT[@]}"; do
         echo "$key -> ${ARMBIAN_COMMANDS_TO_VARS_DICT[$key]}"
     done
 	exit 0 ;
 
-# Main Help Message
-elif [ "$1" == "-h" ]; then
+# Use for doc generation such as man pages, markup/down andor html
+elif [[ "$1" == "--hidden" ]]; then
+	echo -e "\nFor DOC generator\n"
+	exit 0 ;
 
-    doc_build_system
+elif [[ "$1" == "--advanced" || "$1" == "-a" ]]; then
+    source_data
+    advanced_message
+	exit 0 ;
+
+elif [[ "$1" == "--examples" || "$1" == "-e" ]]; then
+    source_data
+    basic_message
+	exit 0 ;
+
+# Main Help Message
+elif [[ "$1" == "-h" ||  "$1" == "--help" ]]; then
+    source_data
+    help_message
 	exit 0 ;
 
 # Otherwise pass options to ./compile.sh
 else
     # Pass args to ./compile.sh
+    cd "$script_dir"
     bash "./compile.sh" "$@"
 fi
