Add 7-zip CPU benchmark to armbianmonitor Unfortunately still people believe into sysbench to be able to report CPU performance

diff --git a/packages/bsp/common/usr/bin/armbianmonitor b/packages/bsp/common/usr/bin/armbianmonitor
--- a/packages/bsp/common/usr/bin/armbianmonitor
+++ b/packages/bsp/common/usr/bin/armbianmonitor
@@ -120,7 +120,7 @@ Main() {
 } # Main
 
 ParseOptions() {
-	while getopts 'hHbBuUrRmMsnNd:Dc:C:pPv' c ; do
+	while getopts 'hHbBuUrRmMsnNd:Dc:C:pPvz' c ; do
 	case ${c} in
 		H)
 			# display full help test
@@ -237,6 +237,11 @@ ParseOptions() {
 			VerifyInstallation
 			exit 0
 			;;
+		z)
+			# Do a quick 7-zip benchmark to estimate CPU performance
+			Run7ZipBenchmark 2>/dev/null
+			exit 0
+			;;
 	esac
 	done
 } # ParseOptions
@@ -259,7 +264,8 @@ DisplayUsage() {
 	echo -e " armbianmonitor ${BOLD}-p${NC} tries to install cpuminer for performance measurements"
 	echo -e " armbianmonitor ${BOLD}-r${NC} tries to install RPi-Monitor"
 	echo -e " armbianmonitor ${BOLD}-u${NC} tries to upload armbian-hardware-monitor.log for support purposes"
-	echo -e " armbianmonitor ${BOLD}-v${NC} tries to verify installed package integrity\n"
+	echo -e " armbianmonitor ${BOLD}-v${NC} tries to verify installed package integrity"
+	echo -e " armbianmonitor ${BOLD}-z${NC} runs a quick 7-zip benchmark to estimate CPU performance\n"
 	echo -e "############################################################################\n"
 } # DisplayUsage
 
@@ -1094,5 +1100,26 @@ kickAllStatsDown() {
 	stxP=0
 	cnt=0
 }
+
+Run7ZipBenchmark() {
+	echo -e "Preparing benchmark. Be patient please..."
+	# Do a quick 7-zip benchmark, check whether binary is there. If not install it
+	MyTool=$(which 7za || which 7zr)
+	[ -z "${MyTool}" ] && apt-get -f -qq -y install p7zip && MyTool=/usr/bin/7zr
+	[ -z "${MyTool}" ] && (echo "No 7-zip binary found and could not be installed. Aborting" >&2 ; exit 1)
+	# Send CLI monitoring to the background to be able to spot throttling and other problems
+	MonitoringOutput="$(mktemp /tmp/${0##*/}.XXXXXX)"
+	trap "rm \"${MonitoringOutput}\" ; exit 0" 0 1 2 3 15
+	armbianmonitor -m >${MonitoringOutput} &
+	MonitoringPID=$!
+	# run 7-zip benchmark after waiting 10 seconds to spot whether the system was idle before
+	sleep 10
+	"${MyTool}" b
+	# report CLI monitoring results as well
+	kill ${MonitoringPID}
+	echo -e "\nMonitoring output recorded while running the benchmark:\n"
+	sed -e '/^\s*$/d' -e '/^Stop/d' <${MonitoringOutput}
+	echo -e "\n"
+} # Run7ZipBenchmark
 
 Main "$@"
