Run package integrity check only as root
Closes #1078

diff --git a/packages/bsp/common/usr/bin/armbianmonitor b/packages/bsp/common/usr/bin/armbianmonitor
--- a/packages/bsp/common/usr/bin/armbianmonitor
+++ b/packages/bsp/common/usr/bin/armbianmonitor
@@ -998,6 +998,12 @@ GetDevice() {
 } # GetDevice
 
 VerifyInstallation() {
+	# Ensure that we're running as root since otherwise querying SATA/USB disks won't work
+	if [ "$(id -u)" != "0" ]; then
+		echo "This check must be run as root. Aborting." >&2
+		exit 1
+	fi
+	
 	echo -e "Starting package integrity check. This might take some time. Be patient please..."
 	OUTPUT=$(dpkg --verify | egrep -v -i "${VerifyRepairExcludes}" | awk -F" /" '{print "/"$2}')
 	if [[ -z $OUTPUT ]]; then
