Additional security check

diff --git a/packages/bsp/common/usr/lib/armbian/armbian-live-patch b/packages/bsp/common/usr/lib/armbian/armbian-live-patch
--- a/packages/bsp/common/usr/lib/armbian/armbian-live-patch
+++ b/packages/bsp/common/usr/lib/armbian/armbian-live-patch
@@ -38,6 +38,13 @@ TMP_DIR=$(mktemp -d -t test-XXXX)
 timeout 10 wget -q --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 3 ${PATCH} -P ${TMP_DIR}
 timeout 10 wget -q --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 3 ${PATCH_SIG} -P ${TMP_DIR}
 
+# Check if installed key is ours. Paranoid mode
+gpg --keyring /usr/share/keyrings/armbian.gpg --list-keys | grep DF00FAF1C577104B50BF1D0093D6889F9F0E78D5
+if [[ $? != 0 ]]; then
+	echo "Warning: signing key invalid or expired"| logger -t "armbian-live-patch"
+	exit 0
+fi
+
 # Check if file is signed with Armbian key
 gpg --keyring /usr/share/keyrings/armbian.gpg --verify ${TMP_DIR}/${PATCH_SIG##*/} ${TMP_DIR}/${PATCH##*/} > ${TMP_DIR}/live-patch.log 2>/dev/null
 
