Removed default passwords for root and htc users

diff --git a/packages/bsp/common/usr/lib/armbian/armbian-firstlogin b/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
--- a/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
+++ b/packages/bsp/common/usr/lib/armbian/armbian-firstlogin
@@ -248,25 +248,31 @@ add_user()
 {
 	read -r -t 0 _
 	REPEATS=3
+
+	# while [ -f "/root/.not_logged_in_yet" ]; do
+	# 	echo -e "\nPlease provide a username (eg. your first name): \c"
+	# 	read -r -e username
+	# 	if ! grep '^[a-zA-Z][a-zA-Z0-9]*$' <<< "$username" > /dev/null ; then
+	# 		echo -e "\n\x1B[91mError\x1B[0m: illegal characters in username"
+	# 		return
+	# 	fi
+
+
+	# 	RealUserName="$(echo "$username" | tr '[:upper:]' '[:lower:]' | tr -d -c '[:alnum:]')"
+	# 	[ -z "$RealUserName" ] && return
+	# 	if ! id "$RealUserName" >/dev/null 2>&1; then break; else echo -e "Username \e[0;31m$RealUserName\x1B[0m already exists on the system."; fi
+	# done
+
+	# User is hardcoded to 'htc' for now
+	username="htc"
+	RealUserName="htc"
+	RealName="HTC User"
+
 	while [ -f "/root/.not_logged_in_yet" ]; do
-		echo -e "\nPlease provide a username (eg. your first name): \c"
-		read -r -e username
-		if ! grep '^[a-zA-Z][a-zA-Z0-9]*$' <<< "$username" > /dev/null ; then
-			echo -e "\n\x1B[91mError\x1B[0m: illegal characters in username"
-			return
-		fi
-
-
-		RealUserName="$(echo "$username" | tr '[:upper:]' '[:lower:]' | tr -d -c '[:alnum:]')"
-		[ -z "$RealUserName" ] && return
-		if ! id "$RealUserName" >/dev/null 2>&1; then break; else echo -e "Username \e[0;31m$RealUserName\x1B[0m already exists on the system."; fi
-	done
-
-	while [ -f "/root/.not_logged_in_yet" ]; do
-		read_password "Create user ($username)"
+		read_password "Enter password for user ($username)"
 		first_input="$password"
 		echo ""
-		read_password "Repeat user ($username)"
+		read_password "Repeat password for user ($username)"
 		second_input="$password"
 		echo ""
 		if [[ "$first_input" == "$second_input" ]]; then
@@ -279,9 +285,7 @@ add_user()
 				fi
 			fi
 			echo -e ""
-			read -r -e -p "Please provide your real name: " -i "${RealUserName^}" RealName
 
-			adduser --quiet --disabled-password --home /home/"$RealUserName" --gecos "$RealName" "$RealUserName"
 			(echo "$first_input";echo "$second_input";) | passwd "$RealUserName" >/dev/null 2>&1
 			for additionalgroup in sudo netdev audio video disk tty users games dialout plugdev input bluetooth systemd-journal ssh; do
 				usermod -aG "${additionalgroup}" "${RealUserName}" 2>/dev/null
