v20190221

diff --git a/config/packages/50-family/shared/scripts/nand-sata-install/nand-sata-install b/config/packages/50-family/shared/scripts/nand-sata-install/nand-sata-install
--- a/config/packages/50-family/shared/scripts/nand-sata-install/nand-sata-install
+++ b/config/packages/50-family/shared/scripts/nand-sata-install/nand-sata-install
@@ -140,9 +140,59 @@ create_armbian()
 	echo -e "\nCopying ${TODO} files to $2. \c" >> $logfile
 
 	# creating rootfs
-	rsync -avrltD --delete --exclude-from=$EX_LIST / ${TempDir}/rootfs | nl | awk '{ printf "%.0f\n", 100*$1/"'"$TODO"'" }' \
-	| dialog --backtitle "$backtitle" --title " $title " --gauge "\n\n  Transferring rootfs to $2 ($USAGE MB). \n\n \
-	This will take approximately $(( $((USAGE/300)) * 5 )) minutes to finish. Please wait!\n\n" 11 80
+	# Speed copy increased x10
+	 # Variables for interfacing with rsync progress
+	nsi_conn_path="/tmp/nand-sata-install"
+	nsi_conn_done="${nsi_conn_path}/done"
+	nsi_conn_progress="${nsi_conn_path}/progress"
+	rm -rf "${nsi_conn_path}"
+	mkdir -p "${nsi_conn_path}"
+	echo 0 >"${nsi_conn_progress}"
+	echo no >"${nsi_conn_done}"
+
+	 # Launch rsync in background
+	{ \
+	rsync -avrltD --delete --exclude-from=$EX_LIST / ${TempDir}/rootfs | \
+	nl | awk '{ printf "%.0f\n", 100*$1/"'"$TODO"'" }' \
+	> "${nsi_conn_progress}" ;
+	 # save exit code from rsync
+	echo  ${PIPESTATUS[0]} >"${nsi_conn_done}"
+	} &
+
+	 # while variables
+	rsync_copy_finish=0
+	rsync_progress=0
+	prev_progress=0
+	rsync_done=""
+	while [ "${rsync_copy_finish}" -eq 0 ]; do
+		# Sometimes reads the progress file while writing and only partial numbers (like 1 when is 15)
+		prev_progress=${rsync_progress}
+		rsync_progress=$(tail -n1 "${nsi_conn_progress}")
+		if [[ -z ${rsync_progress} ]]; then
+			rsync_progress=${prev_progress}
+		fi
+		if [ ${prev_progress} -gt ${rsync_progress} ]; then
+			rsync_progress=${prev_progress}
+		fi
+		echo "${rsync_progress}"
+		# finish the while if the rsync is finished
+		rsync_done=$(cat ${nsi_conn_done})
+		if [[ "${rsync_done}" != "no" ]]; then
+			if [[ ${rsync_done} -eq 0 ]]; then
+				rm -rf "${nsi_conn_path}"
+				rsync_copy_finish=1
+			else
+				# if rsync return error
+				echo "Error: could not copy rootfs files, exiting"
+				exit 1
+			fi
+		else
+			sleep 0.5
+		fi
+
+	done | \
+	dialog --backtitle "$backtitle" --title " $title " --gauge "\n\n  Transferring rootfs to $2 ($USAGE MB). \n\n \
+	 This will take approximately $(( $((USAGE/300)) * 1 )) minutes to finish. Please wait!\n\n" 11 80
 
 	# run rsync again to silently catch outstanding changes between / and ${TempDir}/rootfs/
 	dialog --title "$title" --backtitle "$backtitle" --infobox "\n  Cleaning up ... Almost done." 5 40
@@ -481,7 +531,7 @@ format_disk()
 check_partitions()
 {
 	IFS=" "
-	AvailablePartitions=$(lsblk -l | awk -F" " '/ part / {print $1}' | egrep '^sd|^nvme')
+	AvailablePartitions=$(lsblk -l | awk -F" " '/ part | raid..? / {print $1}' | egrep '^sd|^nvme|^md')
 	if [[ -z $AvailablePartitions ]]; then
 		dialog --title "$title" --backtitle "$backtitle" --colors --msgbox \
 		"\n\Z1There are no avaliable partitions. Please create them.\Zn" 7 60
@@ -489,7 +539,7 @@ check_partitions()
 		apt-get -y -q install gdisk >/dev/null 2>&1
 		gdisk /dev/$diskcheck
 	fi
-	AvailablePartitions=$(lsblk -l | awk -F" " '/ part / {print $1}' | egrep '^sd|^nvme' | sed 's|^|/dev/|' | nl | xargs echo -n)
+	AvailablePartitions=$(lsblk -l | awk -F" " '/ part | raid..? / {print $1}' | egrep '^sd|^nvme|^md' | uniq | sed 's|^|/dev/|' | nl | xargs echo -n)
 	PartitionOptions=($AvailablePartitions)
 
 	PartitionCmd=(dialog --title "Select destination:" --backtitle "$backtitle" --menu "\n$infos" 10 60 16)
@@ -519,6 +569,21 @@ check_nvme_target()
 
 	[[ $? -ne 0 ]] && exit 1
 	DISK_ROOT_PART=${NVMeOptions[(2*$NVMeChoices)-1]}
+}
+
+# build and update new bootscript
+update_bootscript()
+{
+	if [ -f /boot/boot.cmd.new ]; then
+		mv -f /boot/boot.cmd.new /boot/boot.cmd >/dev/null 2>&1
+		mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr  >/dev/null 2>&1
+	elif [ -f /boot/boot.ini.new ]; then
+		mv -f /boot/boot.ini.new /boot/boot.ini >/dev/null 2>&1
+		rootdev=$(sed -e 's/^.*root=//' -e 's/ .*$//' < /proc/cmdline)
+		rootfstype=$(sed -e 's/^.*rootfstype=//' -e 's/ .*$//' < /proc/cmdline)
+		sed -i "s/setenv rootfstype.*/setenv rootfstype \"$rootfstype\"/" /boot/boot.ini
+		sed -i "s/setenv rootdev.*/setenv rootdev \"$rootdev\"/" /boot/boot.ini
+	fi
 }
 
 # show warning [TEXT]
@@ -646,6 +711,7 @@ main()
 			5)
 				show_warning "This script will update the bootloader on SD/eMMC. Continue?"
 				write_uboot_platform $DIR ${root_partition_device}
+				update_bootscript
 				dialog --backtitle "$backtitle" --title "Writing bootloader" --msgbox "\n          Done." 7 30
 				return
 				;;
@@ -664,6 +730,7 @@ main()
 				MTD_BLK="/dev/${spicheck}"
 				show_warning "This script will update the bootloader on SPI Flash $MTD_BLK. Continue?"
 				write_uboot_platform_mtd $DIR $MTD_BLK
+				update_bootscript
 				echo "Done"
 				return
 				;;
