Update armbian-install
https://armbian.atlassian.net/browse/AR-1001 
added  function to unmount and format MTD flash
added menu entry for said function.

diff --git a/packages/bsp/common/usr/sbin/armbian-install b/packages/bsp/common/usr/sbin/armbian-install
--- a/packages/bsp/common/usr/sbin/armbian-install
+++ b/packages/bsp/common/usr/sbin/armbian-install
@@ -644,6 +644,63 @@ format_disk()
 	dialog --title "$title" --backtitle "$backtitle" --infobox "\nFormating $1 to $FilesystemChoosen ... please wait." 5 60
 	mkfs.${FilesystemChoosen} ${mkopts[$FilesystemChoosen]} "$1" >> $logfile 2>&1
 }
+### formatting MTD partition, examples: /dev/mtd0 or /dev/mtdblock0
+#
+format_mtd()
+{
+ls /tmp/boot
+	# Warning mesage formating removes all data
+	dialog --title "Warning" --yesno "Proceed with caution: \
+	any data on target will be permanently deleted \
+	Are you sure you want to continue?" 7 60
+
+	# Get the exit status of the dialog command
+	response=$?
+
+	# Exit if no is pressed, otherwise continue
+    [[ ! $response -eq 0 ]] && echo -e "User canseled" && exit 1;
+
+    # Find the MTD partition that contains the SPI boot loader
+
+    if [[ ! -e /dev/mtd0 ]]; then
+        echo "MTD not found"
+        return 1
+
+    else
+		# unmount MTD befor formating
+        umount $(mount | grep /dev/mtdblock0 | awk '{print $3}')
+
+		# Erase the MTD and display a progress dialog
+        flash_erase /dev/mtd0 0 0 2>&1 | {
+
+			# Read the output of the flash_erase command line by line
+            while read -r line; do
+
+				# Extract the progress percentage from the line
+                progress=$(echo "$line" | grep -oP '\d+(?=%)')
+
+				# Update the progress dialog
+                echo "XXX"
+                echo "$progress"
+                echo "Erasing MTD partition: $progress% complete"
+                echo "XXX"
+            done
+
+			# unnessary progress guage
+        } | dialog --title "Erasing MTD partition" --gauge "Erasing MTD partition: 0% complete" 10 70 0
+
+		# ENd dialog
+        dialog --title "MTD Erased" --msgbox "The MTD partition has been erased." 10 70
+        rows=$(stty size | cut -d ' ' -f 1)
+		# put the cureser at the end of terminal
+        tput cup $rows 0
+
+    fi
+
+
+	echo ""
+	ls /tmp/boot
+}
 
 
 # choose target SATA/USB/NVMe partition.
@@ -902,6 +959,12 @@ main()
 				;;
 			7)
 				write_uboot_to_mtd_flash "$DIR" "$mtdcheck"
+				return
+				;;
+			8)
+                		title='Format  | MTD Flash'
+                		#show_warning "This script will erase your device $DISK_ROOT_PART. Continue?"
+                		format_mtd
 				return
 				;;
 
