AR-1398: Fix wrong error message when missing fs tools (#4424)

diff --git a/packages/bsp/common/usr/sbin/armbian-install b/packages/bsp/common/usr/sbin/armbian-install
--- a/packages/bsp/common/usr/sbin/armbian-install
+++ b/packages/bsp/common/usr/sbin/armbian-install
@@ -541,6 +541,12 @@ format_emmc()
 		# (convert to sectors for partitioning)
 		DEFAULT_BOOTSIZE_SECTORS=$(((${DEFAULT_BOOTSIZE} * 1024 * 1024) / 512))
 
+		# check if the filesystem tools are actually installed
+		if ! command -v mkfs.${eMMCFilesystemChoosen} >/dev/null 2>&1; then
+			echo "Error: Filesystem tools for ${eMMCFilesystemChoosen} not installed, exiting"
+			exit 9
+		fi
+
 		# check whether swap is currently defined and a new swap partition is needed
 		grep -q swap /etc/fstab
 		case $? in
