Implementing into the script. Still early WIP, some new features are working ...

diff --git a/config/packages/TEMPLATE/armbian.preinst b/config/packages/TEMPLATE/armbian.preinst
--- a/config/packages/TEMPLATE/armbian.preinst
+++ b/config/packages/TEMPLATE/armbian.preinst
@@ -1,3 +1,5 @@
 echo "#!/bin/sh"
-echo "# This script is executed before the package is unpacked."
+echo "# This script is executed after files are unpacked"
+echo "# Exit on error"
+echo "set -e"
 echo "exit 0"
diff --git a/config/packages/TEMPLATE/armbian.prerm b/config/packages/TEMPLATE/armbian.prerm
--- a/config/packages/TEMPLATE/armbian.prerm
+++ b/config/packages/TEMPLATE/armbian.prerm
@@ -1,3 +1,5 @@
 echo "#!/bin/sh"
-echo "# This script is executed before the removal of files associated with the package."
+echo "# This script is executed after files are unpacked"
+echo "# Exit on error"
+echo "set -e"
 echo "exit 0"
