Improved armhwinfo: fixed sun8i detection, enabled logrotation, readonly rootfs warning

diff --git a/scripts/armhwinfo b/scripts/armhwinfo
--- a/scripts/armhwinfo
+++ b/scripts/armhwinfo
@@ -208,6 +208,9 @@ detect_board() {
 
 log_hardware_info() {
 	Log=/var/log/armhwinfo.log
+	[ -d /etc/logrotate.d ! -f "/etc/logrotate.d/${0##*/}" ] && \
+		echo -e "${Log} {\n  rotate 12\n  weekly\n  compress\n  missingok\n  notifempty\n}" \
+		> "/etc/logrotate.d/${0##*/}" ; chmod 644 "/etc/logrotate.d/${0##*/}"
 	if [ -f ${Log} ]; then
 		echo -e "\n\n\n$(date) $HARDWARE $ARCH $KERNELID $MACHINE $ID" >>${Log}
 	else
@@ -249,6 +252,7 @@ case $1 in
 		set_io_scheduler &
 
 		# get hardware informations
+		ifconfig | grep -q eth0 || (ifconfig eth0 up ; sleep 1)
 		collect_informations
 		
 		# hardware detection
@@ -257,6 +261,10 @@ case $1 in
 		# display message, log hardware id to file, write log
 		echo -e "[\e[0;32m ok \x1B[0m] Starting ARM hardware info: $ID"
 		echo $ID > /var/run/machine.id
+		if [ $? -ne 0 ]; then
+			# most probably readonly fs. We'll try to warn the user.
+			show_motd_warning "It seems the rootfs is readonly at the moment. Please check your SD card for errors"
+		fi
 		log_hardware_info
 
 		# crash detection, enable verbose logging and disable it at clean shutdown
