Compacting

diff --git a/tools/repository/repo b/tools/repository/repo
--- a/tools/repository/repo
+++ b/tools/repository/repo
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-#
+
 # Adding package
 #
 # @arg $1 string component
@@ -8,17 +8,14 @@
 # @arg $4 input folder
 #
 adding_packages() {
-
 # add deb files to repository if they are not already there
 for f in "${4}${2}"/*.deb; do
 	local package name version arch
-
 	# read package
 	package=$(dpkg-deb -I "${f}")
 	name=$(echo "${package}" | awk /Package/'{print $2}')
 	version=$(echo "${package}" | awk /Version/'{print $2}')
 	arch=$(echo "${package}" | awk /Architecture/'{print $2}')
-
 	# add if not already there
 	aptly repo search -architectures="${arch}" -config="${CONFIG}" "${1}" \
 	'Name (% '${name}'), $Version (='${version}'), $Architecture (='${arch}')' &> /dev/null
@@ -30,6 +27,7 @@ done
 }
 
 
+# publishing repository
 #
 # $1: Input folder
 # $2: Output folder
@@ -37,116 +35,97 @@ done
 # $4: GPG password
 # $5: jammy,sid
 #
-addtorepo() {
-
-	# read comma delimited distros into array
-    IFS=', ' read -r -a DISTROS <<< "$5"
-	local errors=0
-
-	for release in "${DISTROS[@]}"; do
-
-		local forceoverwrite=""
-
-		# let's drop from publish if exits
-		if [[ -n $(aptly publish list -config="${CONFIG}" -raw | awk '{print $(NF)}' | grep "${release}") ]]; then
-			aptly publish drop -config="${CONFIG}" "${release}" > /dev/null 2>&1
-		fi
-
-		# create local repository if not exist
-		if [[ -z $(aptly repo list -config="${CONFIG}" -raw | awk '{print $(NF)}' | grep "${release}") ]]; then
-			aptly repo create -config="${CONFIG}" -distribution="${release}" -component="main,${release}-utils,${release}-desktop" -comment="Armbian main repository" "${release}"  > /dev/null 2>&1
-		fi
-
-		if [[ -z $(aptly repo list -config="${CONFIG}" -raw | awk '{print $(NF)}' | grep "${release}-utils") ]]; then
-			aptly repo create -config="${CONFIG}" -distribution="${release}" -component="${release}-utils" -comment="Armbian ${release} utilities" "${release}-utils" > /dev/null 2>&1
-		fi
-
-		if [[ -z $(aptly repo list -config="${CONFIG}" -raw | awk '{print $(NF)}' | grep "${release}-desktop") ]]; then
-			aptly repo create -config="${CONFIG}" -distribution="${release}" -component="${release}-desktop" -comment="Armbian ${release} desktop" "${release}-desktop" > /dev/null 2>&1
-		fi
-
-		# adding main
-		if find "$1"/ -maxdepth 1 -type f -name "*.deb" 2> /dev/null | grep -q .; then
-			adding_packages "$release" "" "main" "$1"
-		else
-			aptly repo add -config="${CONFIG}" "${release}" "example.deb" > /dev/null
-		fi
-
-		local COMPONENTS="main"
-
-		# adding release-specific main
-		if find "${1}/${release}" -maxdepth 1 -type f -name "*.deb" 2> /dev/null | grep -q .; then
-			adding_packages "${release}" "/${release}" "release packages" "$1"
-		else
-			# workaround - add dummy package to not trigger error
-			aptly repo add -config="${CONFIG}" "${release}" "example.deb" > /dev/null
-		fi
-
-		# adding release-specific utils
-		if find "${1}/extra/${release}-utils" -maxdepth 1 -type f -name "*.deb" 2> /dev/null | grep -q .; then
-			adding_packages "${release}-utils" "/extra/${release}-utils" "release utils" "$1"
-		else
-			aptly repo add -config="${CONFIG}" "${release}-utils" "example.deb" > /dev/null
-		fi
-		COMPONENTS="${COMPONENTS} ${release}-utils"
-
-		# adding release-specific desktop
-		if find "${1}/extra/${release}-desktop" -maxdepth 1 -type f -name "*.deb" 2> /dev/null | grep -q .; then
-			adding_packages "${release}-desktop" "/extra/${release}-desktop" "desktop" "$1"
-		else
-			# workaround - add dummy package to not trigger error
-			aptly repo add -config="${CONFIG}" "${release}-desktop" "example.deb" > /dev/null
-		fi
-		COMPONENTS="${COMPONENTS} ${release}-desktop"
-
-		local mainnum utilnum desknum
-		mainnum=$(aptly repo show -with-packages -config="${CONFIG}" "${release}" | grep "Number of packages" | awk '{print $NF}')
-		utilnum=$(aptly repo show -with-packages -config="${CONFIG}" "${release}-desktop" | grep "Number of packages" | awk '{print $NF}')
-		desknum=$(aptly repo show -with-packages -config="${CONFIG}" "${release}-utils" | grep "Number of packages" | awk '{print $NF}')
-
-		if [ $mainnum -gt 0 ] && [ $utilnum -gt 0 ] && [ $desknum -gt 0 ]; then
-
-			# publish
-			echo "Publishing ${release}"
-			aptly publish \
-				-acquire-by-hash \
-				-architectures="armhf,arm64,amd64,all" \
-				-passphrase="${4}" \
-				-origin="Armbian" \
-				-label="Armbian" \
-				-config="${CONFIG}" \
-				-component="${COMPONENTS// /,}" \
-				-distribution="${release}" repo "${release}" ${COMPONENTS//main/} > /dev/null
-
-			if [[ $? -ne 0 ]]; then
-				echo "Publishing failed ${release}"
-				errors=$((errors + 1))
-				exit 0
-			fi
-		else
-			errors=$((errors + 1))
-			local err_txt=": All components must be present: main, utils and desktop for first build"
-		fi
-
-	done
-
-	# cleanup
-	aptly db cleanup -config="${CONFIG}" > /dev/null
-
-	# key
-	cp armbian.key "${2}"/public/
-
-	# display what we have
-	(aptly repo list -config="${CONFIG}") | grep -E packages
-
-	# remove debs if no errors found
-	if [[ $errors -eq 0 ]]; then
-			echo "Purging incoming debs"
-			find "${1}" -name "*.deb" -type f -delete
-	else
-		display_alert "There were some problems $err_txt" "leaving incoming directory intact" "err"
+publishing() {
+# read comma delimited distros into array
+IFS=', ' read -r -a DISTROS <<< "$5"
+local errors=0
+for release in "${DISTROS[@]}"; do
+	local forceoverwrite=""
+	# let's drop from publish if exits
+	if [[ -n $(aptly publish list -config="${CONFIG}" -raw | awk '{print $(NF)}' | grep "${release}") ]]; then
+		aptly publish drop -config="${CONFIG}" "${release}" > /dev/null 2>&1
 	fi
-
+	# create local repository if not exist
+	if [[ -z $(aptly repo list -config="${CONFIG}" -raw | awk '{print $(NF)}' | grep "${release}") ]]; then
+		aptly repo create -config="${CONFIG}" -distribution="${release}" \
+		-component="main,${release}-utils,${release}-desktop" -comment="Armbian main repository" "${release}"  > /dev/null 2>&1
+	fi
+	if [[ -z $(aptly repo list -config="${CONFIG}" -raw | awk '{print $(NF)}' | grep "${release}-utils") ]]; then
+		aptly repo create -config="${CONFIG}" -distribution="${release}" \
+		-component="${release}-utils" -comment="Armbian ${release} utilities" "${release}-utils" > /dev/null 2>&1
+	fi
+	if [[ -z $(aptly repo list -config="${CONFIG}" -raw | awk '{print $(NF)}' | grep "${release}-desktop") ]]; then
+		aptly repo create -config="${CONFIG}" -distribution="${release}" \
+		-component="${release}-desktop" -comment="Armbian ${release} desktop" "${release}-desktop" > /dev/null 2>&1
+	fi
+	# adding main
+	if find "$1"/ -maxdepth 1 -type f -name "*.deb" 2> /dev/null | grep -q .; then
+		adding_packages "$release" "" "main" "$1"
+	else
+		aptly repo add -config="${CONFIG}" "${release}" "example.deb" > /dev/null
+	fi
+	local COMPONENTS="main"
+	# adding release-specific main
+	if find "${1}/${release}" -maxdepth 1 -type f -name "*.deb" 2> /dev/null | grep -q .; then
+		adding_packages "${release}" "/${release}" "release packages" "$1"
+	else
+		# workaround - add dummy package to not trigger error
+		aptly repo add -config="${CONFIG}" "${release}" "example.deb" > /dev/null
+	fi
+	# adding release-specific utils
+	if find "${1}/extra/${release}-utils" -maxdepth 1 -type f -name "*.deb" 2> /dev/null | grep -q .; then
+		adding_packages "${release}-utils" "/extra/${release}-utils" "release utils" "$1"
+	else
+		aptly repo add -config="${CONFIG}" "${release}-utils" "example.deb" > /dev/null
+	fi
+	COMPONENTS="${COMPONENTS} ${release}-utils"
+	# adding release-specific desktop
+	if find "${1}/extra/${release}-desktop" -maxdepth 1 -type f -name "*.deb" 2> /dev/null | grep -q .; then
+		adding_packages "${release}-desktop" "/extra/${release}-desktop" "desktop" "$1"
+	else
+		# workaround - add dummy package to not trigger error
+		aptly repo add -config="${CONFIG}" "${release}-desktop" "example.deb" > /dev/null
+	fi
+	COMPONENTS="${COMPONENTS} ${release}-desktop"
+	local mainnum utilnum desknum
+	mainnum=$(aptly repo show -with-packages -config="${CONFIG}" "${release}" | grep "Number of packages" | awk '{print $NF}')
+	utilnum=$(aptly repo show -with-packages -config="${CONFIG}" "${release}-desktop" | grep "Number of packages" | awk '{print $NF}')
+	desknum=$(aptly repo show -with-packages -config="${CONFIG}" "${release}-utils" | grep "Number of packages" | awk '{print $NF}')
+	if [ $mainnum -gt 0 ] && [ $utilnum -gt 0 ] && [ $desknum -gt 0 ]; then
+		# publish
+		echo "Publishing ${release}"
+		aptly publish \
+			-acquire-by-hash \
+			-architectures="armhf,arm64,amd64,all" \
+			-passphrase="${4}" \
+			-origin="Armbian" \
+			-label="Armbian" \
+			-config="${CONFIG}" \
+			-component="${COMPONENTS// /,}" \
+			-distribution="${release}" repo "${release}" ${COMPONENTS//main/} > /dev/null
+		if [[ $? -ne 0 ]]; then
+			echo "Publishing failed ${release}"
+			errors=$((errors + 1))
+			exit 0
+		fi
+	else
+		errors=$((errors + 1))
+		local err_txt=": All components must be present: main, utils and desktop for first build"
+	fi
+done
+# cleanup
+aptly db cleanup -config="${CONFIG}" > /dev/null
+# key
+cp armbian.key "${2}"/public/
+# display what we have
+(aptly repo list -config="${CONFIG}") | grep -E packages
+# remove debs if no errors found
+if [[ $errors -eq 0 ]]; then
+		echo "Purging incoming debs"
+		find "${1}" -name "*.deb" -type f -delete
+else
+	display_alert "There were some problems $err_txt" "leaving incoming directory intact" "err"
+fi
 }
 
 
@@ -159,81 +138,78 @@ addtorepo() {
 #
 repo-manipulate() {
 
-	# read comma delimited distros into array
-	IFS=', ' read -r -a DISTROS <<< "$5"
+# read comma delimited distros into array
+IFS=', ' read -r -a DISTROS <<< "$5"
 
-	case $3 in
+case $3 in
 
-		serve)
+	serve)
 
-			sudo aptly serve -listen=$(ip -f inet addr | grep -Po 'inet \K[\d.]+' | grep -v 127.0.0.1 | head -1):80 -config="${CONFIG}"
-			return 0
+		sudo aptly serve -listen=$(ip -f inet addr | grep -Po 'inet \K[\d.]+' | grep -v 127.0.0.1 | head -1):80 -config="${CONFIG}"
+		return 0
+	;;
 
-			;;
+	show)
 
-		show)
+		for release in "${DISTROS[@]}"; do
+			echo "Displaying repository contents for $release"
+			aptly repo show -with-packages -config="${CONFIG}" "${release}" | tail -n +7
+			echo "Displaying repository contents for $release-utils"
+			aptly repo show -with-packages -config="${CONFIG}" "${release}-utils" | tail -n +7
+			echo "Displaying repository contents for $release-desktop"
+			aptly repo show -with-packages -config="${CONFIG}" "${release}-desktop" | tail -n +7
+		done
+		return 0
+	;;
 
+	unique)
+		# which package should be removed from all repositories
+		IFS=$'\n'
+		while true; do
+			LIST=()
 			for release in "${DISTROS[@]}"; do
-				echo "Displaying repository contents for $release"
-				aptly repo show -with-packages -config="${CONFIG}" "${release}" | tail -n +7
-				echo "Displaying repository contents for $release-utils"
-				aptly repo show -with-packages -config="${CONFIG}" "${release}-utils" | tail -n +7
-				echo "Displaying repository contents for $release-desktop"
-				aptly repo show -with-packages -config="${CONFIG}" "${release}-desktop" | tail -n +7
+				LIST+=($(aptly repo show -with-packages -config="${CONFIG}" "${release}" | tail -n +7))
+				LIST+=($(aptly repo show -with-packages -config="${CONFIG}" "${release}-utils" | tail -n +7))
+				LIST+=($(aptly repo show -with-packages -config="${CONFIG}" "${release}-desktop" | tail -n +7))
 			done
-			return 0
-
-			;;
-
-		unique)
-
-			# which package should be removed from all repositories
-			IFS=$'\n'
-			while true; do
-				LIST=()
+			LIST=($(echo "${LIST[@]}" | tr ' ' '\n' | sort -u))
+			new_list=()
+			# create a human readable menu
+			for ((n = 0; n < $((${#LIST[@]})); n++)); do
+				new_list+=("${LIST[$n]}")
+				new_list+=("")
+			done
+			LIST=("${new_list[@]}")
+			LIST_LENGTH=$((${#LIST[@]} / 2))
+			exec 3>&1
+			TARGET_VERSION=$(dialog --cancel-label "Cancel" --backtitle "BACKTITLE" --no-collapse --title \
+			"Remove packages from repositories" --clear --menu "Delete" $((9 + LIST_LENGTH)) 82 65 "${LIST[@]}" 2>&1 1>&3)
+			exitstatus=$?
+			exec 3>&-
+			if [[ $exitstatus -eq 0 ]]; then
 				for release in "${DISTROS[@]}"; do
-					LIST+=($(aptly repo show -with-packages -config="${CONFIG}" "${release}" | tail -n +7))
-					LIST+=($(aptly repo show -with-packages -config="${CONFIG}" "${release}-utils" | tail -n +7))
-					LIST+=($(aptly repo show -with-packages -config="${CONFIG}" "${release}-desktop" | tail -n +7))
+					aptly repo remove -config="${CONFIG}" "${release}" "$TARGET_VERSION"
+					aptly repo remove -config="${CONFIG}" "${release}-utils" "$TARGET_VERSION"
+					aptly repo remove -config="${CONFIG}" "${release}-desktop" "$TARGET_VERSION"
 				done
-				LIST=($(echo "${LIST[@]}" | tr ' ' '\n' | sort -u))
-				new_list=()
-				# create a human readable menu
-				for ((n = 0; n < $((${#LIST[@]})); n++)); do
-					new_list+=("${LIST[$n]}")
-					new_list+=("")
-				done
-				LIST=("${new_list[@]}")
-				LIST_LENGTH=$((${#LIST[@]} / 2))
-				exec 3>&1
-				TARGET_VERSION=$(dialog --cancel-label "Cancel" --backtitle "BACKTITLE" --no-collapse --title "Remove packages from repositories" --clear --menu "Delete" $((9 + LIST_LENGTH)) 82 65 "${LIST[@]}" 2>&1 1>&3)
-				exitstatus=$?
-				exec 3>&-
-				if [[ $exitstatus -eq 0 ]]; then
-					for release in "${DISTROS[@]}"; do
-						aptly repo remove -config="${CONFIG}" "${release}" "$TARGET_VERSION"
-						aptly repo remove -config="${CONFIG}" "${release}-utils" "$TARGET_VERSION"
-						aptly repo remove -config="${CONFIG}" "${release}-desktop" "$TARGET_VERSION"
-					done
-				else
-					return 1
-				fi
-				aptly db cleanup -config="${CONFIG}" > /dev/null 2>&1
-			done
-			;;
+			else
+				return 1
+			fi
+			aptly db cleanup -config="${CONFIG}" > /dev/null 2>&1
+			# remove empty folders
+			find $2/public -type d -empty -print -exec rm -rf {} \;
+		done
+		;;
 
-		update)
+	update)
+		publishing "$1" "$2" "$3" "$4" "$5"
+		;;
 
-			addtorepo "$1" "$2" "$3" "$4" "$5"
-			;;
-
-		*)
-
-			echo -e "Unknown command"
-			return 1
-			;;
-
-	esac
+	*)
+		echo -e "Unknown command"
+		return 1
+		;;
+esac
 }
 
 
