Cleanup

diff --git a/tools/repository/repo b/tools/repository/repo
--- a/tools/repository/repo
+++ b/tools/repository/repo
@@ -155,29 +155,37 @@ showall
 }
 
 
-# signing repository
-#
-# $1: Input folder
-# $2: Output folder
-# $3: Command
-# $4: GPG password
-# $5: jammy,sid
+# Sign repository Release files in the given output folder using provided GPG keys
+# $1: Output folder path
+# $@: GPG key IDs to use for signing
+signing() {
+    local output_folder="$1"
+    shift
+    local gpg_keys=("$@")
 
-signing(){
-		GPG_PARAMETERS=(
-			"--yes"
-			"--armor"
-			"-u" "DF00FAF1C577104B50BF1D0093D6889F9F0E78D5" # Igor Pecovnik (Ljubljana, Slovenia) <igor.pecovnik@gmail.com>
-			"-u" "8CFA83D13EB2181EEF5843E41EB30FAF236099FE" # Armbian Repository Signing Key (Repository Key) <info@armbian.com>
-		)
-		for i in "$2"/public/dists/*/Release
-		do
-			DISTRO_PATH="$(dirname "$i")"
-			echo $DISTRO_PATH
-			gpg "${GPG_PARAMETERS[@]}" --clear-sign -o "$DISTRO_PATH/InRelease" "$i"
-			gpg "${GPG_PARAMETERS[@]}" --detach-sign -o "$DISTRO_PATH/Release.gpg" "$i"
-		done
+    if [[ ${#gpg_keys[@]} -eq 0 ]]; then
+        echo "No GPG keys provided for signing." >&2
+        return 1
+    fi
+
+    local gpg_params=("--yes" "--armor")
+    for key in "${gpg_keys[@]}"; do
+        if ! gpg --list-secret-keys "$key" >/dev/null 2>&1; then
+            echo "Warning: GPG key $key not found on this system." >&2
+			continue
+        fi
+        gpg_params+=("-u" "$key")
+    done
+
+    find "$output_folder/public/dists" -type f -name Release | while read -r release_file; do
+        local distro_path
+        distro_path="$(dirname "$release_file")"
+        echo "Signing release at: $distro_path" | sudo tee -a "$DEBUGFILE"
+        gpg "${gpg_params[@]}" --clear-sign -o "$distro_path/InRelease" "$release_file"
+        gpg "${gpg_params[@]}" --detach-sign -o "$distro_path/Release.gpg" "$release_file"
+    done
 }
+
 
 #
 # $1: Input folder
@@ -274,9 +282,8 @@ case $3 in
 		# remove old releases from publishing
 		drop_unsupported_releases "all"
 		publishing "$1" "$2" "$3" "$4" "$5"
-		signing "$1" "$2" "$3" "$4" "$5"
+		signing "$2" "DF00FAF1C577104B50BF1D0093D6889F9F0E78D5" "8CFA83D13EB2181EEF5843E41EB30FAF236099FE" "x"
 		;;
-
 	*)
 		echo -e "Unknown command"
 		return 1
