Skip scripts folder cleaning if build process native.
Skip creating  postinst prerm scripts  for headers.

diff --git a/packages/armbian/builddeb b/packages/armbian/builddeb
--- a/packages/armbian/builddeb
+++ b/packages/armbian/builddeb
@@ -362,11 +362,18 @@ if [ "$ARCH" != "um" ]; then
 	create_package $libc_headers_packagename $libc_headers_dir
 
 	if is_enabled CONFIG_MODULES; then
-		# Clean up the executables that are left over from
-		# cross-compilation for a different host architecture.
-		(cd $srctree; make M=scripts clean;)
-		deploy_kernel_headers $kernel_headers_dir
-		create_package $kernel_headers_packagename $kernel_headers_dir "headers"
+
+		if is_native ; then
+			# echo "Skip clean scripts folder" >&2
+			deploy_kernel_headers $kernel_headers_dir
+			create_package $kernel_headers_packagename $kernel_headers_dir
+		else
+			# Clean up the executables that are left over from
+			# cross-compilation for a different host architecture.
+			(cd $srctree; make M=scripts clean;)
+			deploy_kernel_headers $kernel_headers_dir
+			create_package $kernel_headers_packagename $kernel_headers_dir "headers"
+		fi
 	fi
 
 fi
