Update maintain.yml

diff --git a/.github/workflows/maintain.yml b/.github/workflows/maintain.yml
--- a/.github/workflows/maintain.yml
+++ b/.github/workflows/maintain.yml
@@ -133,11 +133,12 @@ jobs:
               sudo mount nas:/tank/armbian/dl.armbian.com/_rootfs cache/rootfs
           else
               sudo rsync --size-only --delete -avr rsync://rsync.armbian.com/dl/_rootfs/. cache/rootfs/
-          fi         
-          lz4 -tqq cache/rootfs/${CHUNK}
-          if [[ $? -ne 0 ]]; then
-              display_alert "Integrity check failed" "Removing $file" "err"
-              rm ${file}*
-          else
-              display_alert "Integrity checking" "$file" "info"
           fi
+          ls -l
+          #lz4 -tqq cache/rootfs/${CHUNK}
+          #if [[ $? -ne 0 ]]; then
+          #    display_alert "Integrity check failed" "Removing $file" "err"
+          #    rm ${file}*
+          #else
+          #    display_alert "Integrity checking" "$file" "info"
+          #fi
